### ISSUE TITLE
Error: i18n support is not compatible with next export.

### ISSUE THREAD

**Issue by zzxzzk115** [ClockworkPiFans/website#2]
```bash
> npm run export

> clockworkpi-fans-website@0.1.0 export
> next export

info  - using build directory: /Users/mac/website/.next
info  - Copying "static build" directory
info  - No "exportPathMap" found in "/Users/mac/website/next.config.js". Generating map from "./pages"
Error: i18n support is not compatible with next export. See here for more info on deploying: https://nextjs.org/docs/deployment
    at /Users/mac/website/node_modules/next/dist/export/index.js:148:19
    at async Span.traceAsyncFn (/Users/mac/website/node_modules/next/dist/trace/trace.js:79:20)
```

**Comment by zzxzzk115** [comment]
It should be fixed by this:
https://github.com/vercel/next.js/discussions/18957#discussioncomment-1371013
